[View in Colaboratory](https://colab.research.google.com/github/psm1996/ss/blob/master/digit_prediction.ipynb)

In [1]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

Preconfiguring packages ...
Selecting previously unselected package cron.
(Reading database ... 18396 files and directories currently installed.)
Preparing to unpack .../00-cron_3.0pl1-128ubuntu5_amd64.deb ...
Unpacking cron (3.0pl1-128ubuntu5) ...
Selecting previously unselected package libapparmor1:amd64.
Preparing to unpack .../01-libapparmor1_2.11.0-2ubuntu17.1_amd64.deb ...
Unpacking libapparmor1:amd64 (2.11.0-2ubuntu17.1) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../02-libdbus-1-3_1.10.22-1ubuntu1_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Selecting previously unselected package dbus.
Preparing to unpack .../03-dbus_1.10.22-1ubuntu1_amd64.deb ...
Unpacking dbus (1.10.22-1ubuntu1) ...
Preparing to unpack .../04-gnupg_2.1.15-1ubuntu8.1_amd64.deb ...
Unpacking gnupg (2.1.15-1ubuntu8.1) over (2.1.15-1ubuntu8) ...
Preparing to unpack .../05-gnupg-agent_2.1.15-1ubuntu8.1_amd64.deb ...
Unpacking gnupg-agent (2.1.15-1ubuntu8

Setting up gir1.2-glib-2.0:amd64 (1.54.1-1) ...
Processing triggers for libc-bin (2.26-0ubuntu2.1) ...
Setting up libapparmor1:amd64 (2.11.0-2ubuntu17.1) ...
Setting up unattended-upgrades (0.98ubuntu1.1) ...

Creating config file /etc/apt/apt.conf.d/20auto-upgrades with new version

Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up gnupg-agent (2.1.15-1ubuntu8.1) ...
Setting up dirmngr (2.1.15-1ubuntu8.1) ...
Setting up cron (3.0pl1-128ubuntu5) ...
Adding group `crontab' (GID 102) ...
Done.
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: stop runlevel arguments (1) do not match cron Default-Stop values (none)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Setting up kmod 

In [3]:
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive


In [0]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM


data = [[[i+j] for i in range(3)] for j in range (100)]
data = np.array(data, dtype=float)
target = [[i+3 for i in range(100)]]
target = np.array(target, dtype=float)

In [21]:
data

array([[[  0.],
        [  1.],
        [  2.]],

       [[  1.],
        [  2.],
        [  3.]],

       [[  2.],
        [  3.],
        [  4.]],

       [[  3.],
        [  4.],
        [  5.]],

       [[  4.],
        [  5.],
        [  6.]],

       [[  5.],
        [  6.],
        [  7.]],

       [[  6.],
        [  7.],
        [  8.]],

       [[  7.],
        [  8.],
        [  9.]],

       [[  8.],
        [  9.],
        [ 10.]],

       [[  9.],
        [ 10.],
        [ 11.]],

       [[ 10.],
        [ 11.],
        [ 12.]],

       [[ 11.],
        [ 12.],
        [ 13.]],

       [[ 12.],
        [ 13.],
        [ 14.]],

       [[ 13.],
        [ 14.],
        [ 15.]],

       [[ 14.],
        [ 15.],
        [ 16.]],

       [[ 15.],
        [ 16.],
        [ 17.]],

       [[ 16.],
        [ 17.],
        [ 18.]],

       [[ 17.],
        [ 18.],
        [ 19.]],

       [[ 18.],
        [ 19.],
        [ 20.]],

       [[ 19.],
        [ 20.],
        [ 21.]],



In [25]:
target

array([[  3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,
         14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
         36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,
         47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,
         58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,
         69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,
         80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101.,
        102.]])

In [0]:
leng=3

data = [[i+j for j in range(leng)] for i in range(100)]
data = np.array(data, dtype=np.float32)
target = [[i+j+1 for j in range(leng)] for i in range(1,101)]
target = np.array(target, dtype=np.float32)

data = data.reshape(100, 1, leng)/200
target = target.reshape(100,1,leng)/200

In [33]:
data

array([[[0.   , 0.005, 0.01 ]],

       [[0.005, 0.01 , 0.015]],

       [[0.01 , 0.015, 0.02 ]],

       [[0.015, 0.02 , 0.025]],

       [[0.02 , 0.025, 0.03 ]],

       [[0.025, 0.03 , 0.035]],

       [[0.03 , 0.035, 0.04 ]],

       [[0.035, 0.04 , 0.045]],

       [[0.04 , 0.045, 0.05 ]],

       [[0.045, 0.05 , 0.055]],

       [[0.05 , 0.055, 0.06 ]],

       [[0.055, 0.06 , 0.065]],

       [[0.06 , 0.065, 0.07 ]],

       [[0.065, 0.07 , 0.075]],

       [[0.07 , 0.075, 0.08 ]],

       [[0.075, 0.08 , 0.085]],

       [[0.08 , 0.085, 0.09 ]],

       [[0.085, 0.09 , 0.095]],

       [[0.09 , 0.095, 0.1  ]],

       [[0.095, 0.1  , 0.105]],

       [[0.1  , 0.105, 0.11 ]],

       [[0.105, 0.11 , 0.115]],

       [[0.11 , 0.115, 0.12 ]],

       [[0.115, 0.12 , 0.125]],

       [[0.12 , 0.125, 0.13 ]],

       [[0.125, 0.13 , 0.135]],

       [[0.13 , 0.135, 0.14 ]],

       [[0.135, 0.14 , 0.145]],

       [[0.14 , 0.145, 0.15 ]],

       [[0.145, 0.15 , 0.155]],

       [[0

In [29]:
target

array([[[0.01 , 0.015, 0.02 ]],

       [[0.015, 0.02 , 0.025]],

       [[0.02 , 0.025, 0.03 ]],

       [[0.025, 0.03 , 0.035]],

       [[0.03 , 0.035, 0.04 ]],

       [[0.035, 0.04 , 0.045]],

       [[0.04 , 0.045, 0.05 ]],

       [[0.045, 0.05 , 0.055]],

       [[0.05 , 0.055, 0.06 ]],

       [[0.055, 0.06 , 0.065]],

       [[0.06 , 0.065, 0.07 ]],

       [[0.065, 0.07 , 0.075]],

       [[0.07 , 0.075, 0.08 ]],

       [[0.075, 0.08 , 0.085]],

       [[0.08 , 0.085, 0.09 ]],

       [[0.085, 0.09 , 0.095]],

       [[0.09 , 0.095, 0.1  ]],

       [[0.095, 0.1  , 0.105]],

       [[0.1  , 0.105, 0.11 ]],

       [[0.105, 0.11 , 0.115]],

       [[0.11 , 0.115, 0.12 ]],

       [[0.115, 0.12 , 0.125]],

       [[0.12 , 0.125, 0.13 ]],

       [[0.125, 0.13 , 0.135]],

       [[0.13 , 0.135, 0.14 ]],

       [[0.135, 0.14 , 0.145]],

       [[0.14 , 0.145, 0.15 ]],

       [[0.145, 0.15 , 0.155]],

       [[0.15 , 0.155, 0.16 ]],

       [[0.155, 0.16 , 0.165]],

       [[0

In [41]:
model = Sequential()  
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.add(LSTM(leng, input_shape=(1, leng),return_sequences=True,activation='sigmoid'))
model.compile(loss='mse', optimizer='adam',metrics=['accuracy'])
model.fit(data, target, nb_epoch=10, batch_size=50,validation_data=(data,target))


predict = model.predict(data)

/usr/local/lib/python3.6/dist-packages/keras/models.py:981: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Train on 100 samples, validate on 100 samples
Epoch 1/10
100/100 [==============================] - 5s 54ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 2/10
100/100 [==============================] - 0s 1ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 3/10
100/100 [==============================] - 0s 1ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 4/10
100/100 [==============================] - 0s 1ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 5/10
100/100 [==============================] - 0s 1ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 6/10
100/100 [==============================] - 0s 1ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 7/10
100/100 [==============================] - 0s 1ms/step - loss: 0.0209 - acc: 1.0000 - val_loss: 0.0209 - val_acc: 1.0000
Epoch 8/10
100/100 [=========

In [35]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 1, 3)              84        
Total params: 84
Trainable params: 84
Non-trainable params: 0
_________________________________________________________________
